apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
  labels:
    app: immich
spec:
  capacity:
    storage: 9Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=3
    - rsize=524288
    - wsize=524288
    - hard
    - proto=tcp
  nfs:
    server: 192.168.100.2
    path: /volume1/IMMICH
  claimRef:
    name: immich-library
    namespace: immich
