apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.10-1.1.1
  instances: 1

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: true
        inherit: true
        passwordSecret:
          name: immich-db-credentials

  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance;
        - CREATE EXTENSION IF NOT EXISTS pg_trgm;
        - CREATE EXTENSION IF NOT EXISTS unaccent;
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

  storage:
    size: 10Gi
    storageClass: local-path

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi
