apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "labforge.fullname" . }}-tailscale
  labels:
    {{- include "labforge.labels" . | nindent 4 }}
spec:
  ingressClassName: tailscale
  rules:
    - host: {{ .Values.tailscale.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "labforge.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.tailscale.hostname | quote }}
