gatus:
  ingress:
    enabled: true
    hosts:
      - gatus.home.shatadru.in

  serviceMonitor:
    enabled: true
    interval: 60s
    scrapeTimeout: 30s

  config:
    endpoints:
      - name: Immich
        group: apps
        url: https://photos.shatadru.in
        interval: 60s
        conditions:
          - "[STATUS] == 200"

      - name: shatadru.in
        group: websites
        url: https://shatadru.in
        interval: 60s
        conditions:
          - "[STATUS] == 200"

      - name: sonalstudio.in
        group: websites
        url: https://sonalstudio.in/
        interval: 60s
        conditions:
          - "[STATUS] == 200"

      - name: Argo CD
        group: homelab
        url: https://argocd.home.shatadru.in
        interval: 60s
        conditions:
          - "[STATUS] == 200"

      - name: Grafana
        group: homelab
        url: https://grafana.home.shatadru.in/api/health
        interval: 60s
        conditions:
          - "[STATUS] == 200"

      - name: Prometheus
        group: homelab
        url: https://prometheus.home.shatadru.in/-/healthy
        interval: 60s
        conditions:
          - "[STATUS] == 200"

      - name: Alertmanager
        group: homelab
        url: https://alertmanager.home.shatadru.in/-/healthy
        interval: 60s
        conditions:
          - "[STATUS] == 200"

      - name: Gatus
        group: homelab
        url: https://gatus.home.shatadru.in
        interval: 60s
        conditions:
          - "[STATUS] == 200"
