---
apiVersion: v2
name: local-path-wrapper
description: GitOps wrapper for the Rancher local-path-provisioner Helm chart
type: application
version: 0.1.0

# renovate: datasource=helm depName=local-path-provisioner registryUrl=oci://ghcr.io/rancher/local-path-provisioner/charts
dependencies:
  - name: local-path-provisioner
    repository: oci://ghcr.io/rancher/local-path-provisioner/charts
    version: 0.0.37
