apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: labforge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:shatadru/homelab.git
    path: charts/labforge
    targetRevision: main
    helm:
      valueFiles:
        - values-homelab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: labforge
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
