apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:shatadru/homelab.git
    targetRevision: main
    path: charts/opencloud
  destination:
    server: https://kubernetes.default.svc
    namespace: opencloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
