argo-cd:
  configs:
    params:
      server.insecure: true

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      tls: true
      hostname: argocd.home.shatadru.in
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: "500m"
        memory: "512Mi"

  controller:
    metrics:
      serviceMonitor:
        enabled: false
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: "500m"
        memory: "1Gi"

  repoServer:
    metrics:
      serviceMonitor:
        enabled: false
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: "500m"
        memory: "1Gi"

  applicationSet:
    metrics:
      serviceMonitor:
        enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: "200m"
        memory: "256Mi"

  notifications:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: "200m"
        memory: "256Mi"

  dex:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: "200m"
        memory: "256Mi"

  redis:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: "200m"
        memory: "256Mi"
