argo-cd:
  configs:
    params:
      server.insecure: true

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      tls: true
      hostname: argocd.home.shatadru.in

  controller:
    metrics:
      serviceMonitor:

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "500m"
      memory: "1Gi"
        enabled: false

  repoServer:
    metrics:
      serviceMonitor:
        enabled: false

  applicationSet:
    metrics:
      serviceMonitor:
        enabled: false
