{{- if .Values.homelabPool.enabled }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab
  namespace: metallb-system
spec:
  addresses:
{{- range .Values.homelabPool.addresses }}
    - {{ . | quote }}
{{- end }}
{{- end }}
